# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Develop. Fail. Try Again. Repeat.
email: jmstewart00@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will serve as a look back on the events that led to becoming a software and web developer, along with a way to track my lessons learned along the way. 
baseurl: /stewartblog # the subpath of your site, e.g. /blog
url: http://jmstewart00.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CoachStewart7
github_username:  jmstewart00

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
