# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Josh Stewart's Bootcamp S17
email: jmstewart00@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will serve as a way to update those keeping tabs on me
  in both the immediately surrounding area of Central Kentucky and
  back home in my home state of Maryland. I appreciate all the support
  and, in the end, hope you enjoy keeping up with me. 
baseurl: /stewartblog # the subpath of your site, e.g. /blog
url: http://jmstewart00.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CoachStewart7
github_username:  jmstewart00

# Build settings
markdown: kramdown
theme: cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
